site_name: downlow
repo_url: https://github.com/willf/downlow
site_url: https://willf.github.io/downlow
site_description: A bulk downloader with tenacity and grace
site_author: Will Fitzgerald
edit_uri: edit/main/docs/
repo_name: willf/downlow
copyright: Maintained by <a href="https://willf.com">willf</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/downlow"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/willf/downlow
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/downlow

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
